In [1]:
print("hello word")

hello word


Autour de numpy 

In [2]:
import numpy as np 

rev = [100, 1000, 2000.0, 4000, 3000, 200 , 345, 123, 34500]
rev_array = np.array(rev)

print(rev_array.dtype) # show the type of array 

rev_selec = rev_array[(rev_array>100) & (rev_array < 1000)]

print("rev selct = ", rev_selec )

float64
rev selct =  [200. 345. 123.]


Création de tableau 

In [3]:
# crée un tableau de random comprise entre 0 et 1
rand01 = np.random.random((6,3)) 

print("tab of random value from 0 to 1 = ", rand01)

# Crée un tableau de random d'entier 
randint = np.random.randint(0, 10,size=(5,4))

print("tab of random integer = ", randint)

# ajouter une lingne à un tableau existant 
line = [0, 4, 6, 123]

randint = np.vstack((randint, line)) # see also hstack 

print("modified tab randint = ", randint)

tab of random value from 0 to 1 =  [[0.15022619 0.40581075 0.21756579]
 [0.44957785 0.08329981 0.35167535]
 [0.08899193 0.25234085 0.52876357]
 [0.40240401 0.61037561 0.13663419]
 [0.39767216 0.85356096 0.84348762]
 [0.35160426 0.9796459  0.89095673]]
tab of random integer =  [[6 1 5 2]
 [0 9 3 2]
 [8 0 2 5]
 [9 7 2 2]
 [3 1 3 1]]
modified tab randint =  [[  6   1   5   2]
 [  0   9   3   2]
 [  8   0   2   5]
 [  9   7   2   2]
 [  3   1   3   1]
 [  0   4   6 123]]


In [4]:
a = np.linspace(5, 10, 11)

print(a[-3:-1])
print(a)

[9.  9.5]
[ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10. ]


About Pandas module 

In [ ]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

data_csv = pd.read_csv("clients.csv")

print("five fisrt line of the file")
data_csv.head() # show the 5 first line 

print("five last line of file")
data_csv.tail() # show the five last line 

dim = data_csv.shape
print("dim data = ", dim)
#data_json = pd.read_json("clients.json")

In [ ]:
data_csv.dtypes # show the type of all column 

In [ ]:
clients_values = data_csv.values # get the values of data frame 

clients_keys = data_csv.keys # get all the keys 

display(clients_keys())

In [ ]:
clients_mail = data_csv['email']

display(clients_mail)

Modifier le contenu d'une colonne 

In [ ]:
clients = data_csv.copy()

print("befor change of identifiant")
print(clients['identifiant'])

clients['identifiant'] = clients['identifiant']*100


print("After changes")
print(clients['identifiant'])


Créer ou supprimer une colonne 

In [ ]:
clients['id'] = clients['identifiant'] + 2000

clients.head()

In [ ]:
clients.pop('id') # supprimer la colonne 'id'

clients.head()

Renommer une serie 

In [ ]:
#clients.rename(columns = {'identifiant' : 'ide'})

clients.rename(columns = {'identifiant':'ide', 'email':'mail'} , inplace=True) # inplace permet de modifier la data frame sinon ça crée une copie

clients.head()

changement de typage et trie 

In [ ]:
clients['ide'].astype(float) # change type 

#clients.sort_values['ide']

In [ ]:
clients.head()


In [ ]:
clients.sort_values('ide', ascending=False) # tri de la colunne 'ide'

Filtrer des données 

In [ ]:
prets = pd.read_csv('https://raw.githubusercontent.com/benjaminmrl/data-4452741/main/prets.csv')
prets.head()

Selection 